### ISSUE TITLE
Unclear as to how to customize feed output

### ISSUE THREAD

**Issue by 23d1** [studioespresso/craft3-facebook-catalog#2]
Hey there,

I'm a bit unclear as to how to go about customizing the feed output. Essentially, I'm running into issues where image links are relative, and won't be accepted by Facebook, which looks for absolute URLs.
Also, the twig functionality, would those variables and functions go into the product/entry templates, or is there a config.php one could use?

**Comment by janhenckens** [comment]
Hey there, thanks for getting in touch.
- The relative image urls are probably because your Asset Volume doesn't have a full url, the plugin is calling `getUrl()` on the asset element and doesn't interfere with the url itself
- The twig functions should go in a separate template and will return a full feed. This way you can create the route or a url you like, with the elements/products you like, instead of the the default products feed.

**Comment by 23d1** [comment]
Awesome! Thanks @janhenckens. Adding @web/ before the location sorted out the URL output. Makes sense that creating a separate twig-file for the feed would work. I don't have it in front of me currently, but I'm assuming that if I create `/craft/templates/feed/products/facebook.twig`, that will override the route from the plugin?

**Comment by janhenckens** [comment]
It won't overwrite the original plugin route, it will just give you a new route to that template which you can use as your feed (it works like any other craft template at that point)

**Comment by 23d1** [comment]
Got it! Thanks.
