### ISSUE TITLE
Is this still working on craft 3.6 and commerce 3.2?

### ISSUE THREAD

**Issue by masiorama** [studioespresso/craft3-facebook-catalog#9]
Hello, does this module work as expected on the last versions of Craft and Commerce?
I'm asking because it seems to be abandoned (no updates since 2019).
I would try before asking but I am unable to do proper testing for a few days, but still I am curious :) 
Thanks in advance!

**Comment by janhenckens** [comment]
Hey @masiorama, the plugin should still work fine :) I have lost track of this one a bit but there haven't been any issues reported with it.

Note that if you're comfortable with modules and PHP, you should be able to reproduce what the plugin does pretty easily so if that's the case I would build it yourself, since the plugin only covers a pretty standard product setup that won't for more customized setups.

Let me know if you have any questions or if if I can help you out in another way.
